name: Quest
version: ${project.version}
main: com.github.jasgo.quest.Main
api-version: 1.17
authors: [ Jasgo ]
depend: [Citizens]

commands:
  quest:
    description: "/quest"
  q:
    description: "/quest"
  퀘:
    description: "/quest"
  퀘스트:
    description: "/quest"
